data:
  link: "https://docs.google.com/uc?export=download&id=1YGQLQyMgwjTTIcIPv7Cj31O2BX1Fhl5X"
  data_path: "./data"
  extract_path: "./"
  zip_path: "./data.zip"
  split_ratio:
    test_size : 0.3
  class_names:
    0: End of All Restrictions
    1: End of Minimum Speed Limit 60km/h
    2: End of Minimum Speed Limit 80km/h
    3: End of Maximum Speed Limit 40km/h
    4: End of Maximum Speed Limit 50km/h
    5: End of Maximum Speed Limit 60km/h
    6: Minimum Speed Limit 60km/h
    7: Minimum Speed Limit 80km/h
    8: Maximum Speed Limit 30km/h
    9: Maximum Speed Limit 40km/h
    10: Maximum Speed Limit 50km/h
    11: Maximum Speed Limit 60km/h
    12: Maximum Speed Limit 80km/h
  resize: [128, 128]

output: 
  SVM_save_path: "./SVM_model.h5"
  RF_save_path: "./RF_model.pkl"
