data:
  link: "https://docs.google.com/uc?export=download&id=1ReoWq50snsYoqJR6pcFxVc0LjGlIlyqX"
  data_path: "./data"
  extract_path: "./"
  zip_path: "./data.zip"
  split_ratio:
    test_size : 0.4
  class_names:
    0: End of All Restrictions
    1: End of minimum speed limit 60 km/h
    2: End of minimum speed limit 80 km/h
    3: End of speed limit 40 km/h
    4: End of speed limit 50 km/h
    5: End of speed limit 60 km/h
    6: Minimum speed 60km/h
    7: Minimum speed 80km/h
    8: Speed limit 30km/h
    9: Speed limit 40km/h
    10: Speed limit 50km/h
    11: Speed limit 60km/h
    12: Speed limit 80km/h
  resize: [128, 128]

output: 
  plot: True
  model_save_path: "./results/best_model.h5"
  plot_path: "./results"

