data:
  link: "https://docs.google.com/uc?export=download&id=1xsuwwGQEpXYC8Ow_LyuTCV0mVUe9yQTa"
  data_path: "./data"
  zip_path: "./CV_Data.zip"
  train_path: "./data/train"
  test_path: "./data/test"
  image_size: [256, 256]
  augmentations:
    - "flip"
    - "rotation"
    - "zoom"
  split_ratio:
    train: 0.75
    val: 0.25
  class_names:
    0: 40
    1: 50
    2: 60
    3: Other
  resize: [256, 256]

training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  optimizer: "adam"
  loss_function: "categorical_crossentropy"
  metrics:
    - "accuracy"
    - "precision"
    - "recall"

output: 
  plot: True
  model_save_path: "./results/best_model.h5"
  plot_path: "./results"

